name: Build and publish container image
run-name: ${{ github.actor }} is running build/publish
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!"